routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('blog/listdata', 'BlogController@listdata')->name('blog.listdata');
Route::resource('blog', 'BlogController');

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    protected $guarded = [];

    public function category() {
        return $this->belongsToMany('App\Models\Category');
    }
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Models\Blog;
use App\Models\Category;
use Illuminate\Http\Request;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pages.blog.list')->with('headTitle','Blogs');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('pages.blog.add')->with('categories',$categories)->with('headTitle','Add Blogs');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'category_id' => 'required',
            'blog_name' => 'required',
            'blog_description' => 'required'
        ];
        $this->validateForm($request->all(), $rules);

        $blog_data = [
            'blog_name' => $request->blog_name,
            'blog_description' => $request->blog_description,
            'blog_date' => \Carbon\Carbon::now()->format('Y-m-d'),
        ];

        $blog = Blog::create($blog_data);
        $blog->category()->sync($request->category_id);
        return redirect()->route('blog.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function show(Blog $blog)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function edit(Blog $blog)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Blog $blog)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function destroy(Blog $blog)
    {
        //
    }

    public function listdata(Request $request)
    {
        extract($this->DTFilters($request->all()));
        $count = Blog::where('id','>', 0);
        if($search != ''){
            $count->where(function($query) use ($search){
                $query->orwhere("blog_name", "like", "%{$search}%");
            });
        }
        if ($request['status']) {
            $count = $count->where('blog_date',$request['status']);
        }
        $count = $count->count();

        $records["recordsTotal"] = $count;
        $records["recordsFiltered"] = $count;
        $records['data'] = array();
        
        $blogs = Blog::where('id','>', 0)->offset($offset)->limit($limit)->orderBy($sort_column,$sort_order);
        if($search != ''){
            $blogs->where(function($query) use ($search){
                $query->orwhere("blog_name", "like", "%{$search}%");
            });
        }
        if ($request['status']) {
            $blogs = $blogs->where('blog_date',$request['status']);
        }
        $blogs = $blogs->get();

        foreach ($blogs as $blog) {
            $records['data'][] = [
                'blog_name'=>$blog->blog_name,
                'blog_description'=>$blog->blog_description,
                'blog_date'=>\Carbon\Carbon::parse($blog->created_at)->format('Y-m-d'),
                // 'action'=>'<a href='.url('blog/' . $blog->id).'><button name="view" id="view" class="btn btn-primary btn-xs btnView">View</button></a> <a href='.route('blog.destroy' , $blog->id).' class="btnDelete"><button name="delete" id="delete" class="btn btn-danger btn-xs">Delete</button></a> <a href='.url("blog/".$blog->id."/edit").'><button name="edit" id="edit" class="btn btn-warning btn-xs">Edit</button></a>'
            ];
        }
        return $records;
    }
}

resources/views/pages/blog/add.blade.php
@extends('layouts.app')
@section('title') {{ $headTitle }} @endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Insert Blog</div>
                <div class="panel-body">
                    <form class="form-horizontal" method="POST" id="frmAdd" action="{{ route('blog.store') }}">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('category_id') ? ' has-error' : '' }}">
                            <label for="blog_name" class="col-md-4 control-label">Category</label>

                            <div class="col-md-6">
                                <select data-error-container="#category_error" name="category_id[]" id="category_id" class="form-control input-sm select2-multiple" multiple="multiple">
                                    <option value="" disabled>Select Category</option>
                                    @foreach ($categories as $category)
                                        <option value="{{ $category->id }}" {{ (old('category_id') == $category->id) ? 'selected' : '' }}>{{$category->category_name}}</option>
                                    @endforeach
                                </select>
                                <span id="category_error" class="has-error"></span>

                                @if ($errors->has('category_id'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('category_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('blog_name') ? ' has-error' : '' }}">
                            <label for="blog_name" class="col-md-4 control-label">Blog Name</label>

                            <div class="col-md-6">
                                <input id="blog_name" type="text" class="form-control" name="blog_name">

                                @if ($errors->has('blog_name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('blog_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('blog_description') ? ' has-error' : '' }}">
                            <label for="blog_description" class="col-md-4 control-label">Blog Description</label>

                            <div class="col-md-6">
                                <textarea id="blog_description" rows="5" class="form-control" name="blog_description"></textarea>

                                @if ($errors->has('blog_description'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('blog_description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary" id="btn-insert" value="insert">Submit</button>
                                <a href="{{ route('blog.index') }}"> <button type="button" class="btn btn-warning" id="btn-insert" value="insert">Back</button></a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script type="text/javascript">
$(document).ready(function() {
    
    $("#category_id").select2({placeholder: "Select Category"});

    $(document).on('submit','#frmAdd', function(e){
        $("#frmAdd").validate({
            rules: {
                "category_id[]":{required:true},
                blog_name:{required:true},
                blog_description:{required:true}
            },
            messages: {
                category_id:{required:"Please enter category."},
                blog_name:{required:"Please enter blog name.",},
                blog_description:{required:"Please enter blog description.",}
            },
            errorClass: 'help-block',
            errorElement: 'span',
            highlight: function (element) {
                $(element).closest('.form-group').addClass('has-error');
            },
            unhighlight: function (element) {
                $(element).closest('.form-group').removeClass('has-error');
            },
            errorPlacement: function (error, element) {
                if (element.attr("data-error-container")) {
                    error.appendTo(element.attr("data-error-container"));
                } else {
                    error.insertAfter(element);
                }
            }
        });
    });
    $(document).on('submit','#frmAdd', function(e) {
        if ($("#frmAdd").valid()) {
            return true;
        } else {
            return false;
        }
    });
});
</script>
@endpush

resources/views/pages/blog/edit.blade.php
@extends('layouts.app')
@section('title') {{ $headTitle }} @endsection

@section('breadcrumb')
{!! Breadcrumbs::render('edit_store', $store) !!}
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title" id="basic-layout-form">{{ $headTitle }}</h4>
                <a class="heading-elements-toggle">
                    <i class="la la-ellipsis-v font-medium-3"></i>
                </a>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card-content collapse show">
                        <div class="card-body">
                            <form class="form-horizontal" role="form" id="frmEditStore" method="POST" action="{{ route('store.update', $store->id) }}" enctype="multipart/form-data">
                                {{ csrf_field() }}
                                {{ method_field('PUT') }}

                                <div class="form-group{{ $errors->has('store_name') ? ' has-error' : '' }}">
                                    <label class="col-md-6">{!! $mend_sign !!}Store Name</label>
                                    <div class="col-md-12 col-lg-12 col-xl-6">
                                        <div class="position-relative has-icon-left">
                                            <input type="text" placeholder="Enter Store Name" name="store_name" id="store_name" class="form-control" value="{{old('store_name', $store->store_name)}}" />
                                            <div class="form-control-position">
                                                <i class="fa fa-font"></i>
                                            </div>
                                            @if ($errors->has('store_name'))
                                                <span class="danger"><strong>{{ $errors->first('store_name') }}</strong></span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group{{ $errors->has('store_location') ? ' has-error' : '' }}">
                                    <label class="col-md-3 control-label">{!! $mend_sign !!}Store Location</label>
                                    <div class="col-md-12 col-lg-12 col-xl-6">
                                        <div class="position-relative has-icon-left">
                                            <input type="text" placeholder="Enter Store Location" name="store_location" id="store_location" class="form-control" value="{{old('store_location', $store->store_location)}}" data-error-container="#store_location_error"/>
                                            <div class="form-control-position">
                                                <i class="fa fa-map"></i>
                                            </div>
                                            <div id="map" style="width:100%;height:400px"></div>
                                            <span id="store_location_error"></span>
                                        </div>
                                    </div>
                                </div>


                                
                                <div class="margiv-top-10">
                                	<a href="{{ route('store.index') }}"><button type="button" class="btn btn-danger mr-1"><i class="fa fa-arrow-left"></i> Back</button></a>
                                    <button type="submit" class="btn btn-primary btn-glow"><i class="fa fa-check"></i> Save Changes </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script type="text/javascript">
$(document).ready(function() {
	$("#frmEditStore").validate({
        rules: {
            store_name:{
                required:true
            },
            store_location:{
                required:true
            }
        },
        messages: {
            store_name:{
                required:"@lang('validation.required',['attribute'=>'store name'])"
            },
            store_location:{
                required:"@lang('validation.required',['attribute'=>'store location'])"
            }
        },
        errorClass: 'danger',
        errorElement: 'span',
        highlight: function (element) {
           $(element).closest('.form-group').addClass('has-error');
        },
        unhighlight: function (element) {
           $(element).closest('.form-group').removeClass('has-error');
        },
        errorPlacement: function (error, element) {
            if (element.attr("data-error-container")) {
                error.appendTo(element.attr("data-error-container"));
            } else {
                error.insertAfter(element);
            }
        }
    });
    $(document).on('submit','#frmEditStore',function(){
        if($("#frmEditStore").valid()) {
            return true;
        }else {
            return false;
        }
    });
});

//GOOGLE MAP
function initAutocomplete() {
    var map = new google.maps.Map(document.getElementById('map'), {
        center: {lat:{{ ($store->store_latitude != 0) ? $store->store_latitude : 42.7288916 }}, lng: {{ ($store->store_longitude != 0) ? $store->store_longitude : -87.7847695 }} },
        zoom: 16,
        mapTypeId: google.maps.MapTypeId.ROADMAP,
        mapTypeControl: false
    });

    var marker = new google.maps.Marker({map: map});
    var geocoder = new google.maps.Geocoder();
  
    // Create the search box and link it to the UI element.
    var input = document.getElementById('store_location');
    var searchBox = new google.maps.places.SearchBox(input);

    // Bias the SearchBox results towards current map's viewport.
    map.addListener('bounds_changed', function() {
        searchBox.setBounds(map.getBounds());
    });

    var markers = [];

    @if ($store->store_location != "")
        markers.push(new google.maps.Marker({
            map: map,
            position: {lat:{{ $store->store_latitude }}, lng: {{ $store->store_longitude }} }
        }));
    @endif

    // Listen for the event fired when the user selects a prediction and retrieve more details for that place.
    searchBox.addListener('places_changed', function() {
        var places = searchBox.getPlaces();
        if (places.length == 0) {
            return;
        }
        // Clear out the old markers.
        markers.forEach(function(marker) {
            marker.setMap(null);
        });
        markers = [];
        // For each place, get the icon, name and location.
        var bounds = new google.maps.LatLngBounds();
        places.forEach(function(place) {
            // Create a marker for each place.
            markers.push(new google.maps.Marker({
                map: map,
                title: place.name,
                position: place.geometry.location
            }));

            if (place.geometry) {
                marker.setPosition(place.geometry.location);
                if (place.geometry.viewport) {
                    // Only geocodes have viewport.
                    bounds.union(place.geometry.viewport);
                } else {
                    bounds.extend(place.geometry.location);
                }
            }
        });
        map.fitBounds(bounds);
    });
}
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC7kiVlXV3vw-HjT_9UmKEoJ5su1KXJrBA&libraries=places&callback=initAutocomplete" type="text/javascript">
</script>
</script>
@endpush

resources/views/pages/blog/list.blade.php
@extends('layouts.app')
@section('title') {{ $headTitle }} @endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href="{{ url('blog/create') }}"><button name="add" id="btn-add" class="btn btn-success btn-sm pull-right" style="margin-top: -5px;">Add</button></a>
                </div>
                <div class="row">
                    <label for="filter" class="col-md-2 control-label">Date Filter</label>
                    <div class='col-md-4 input-group date' id='filter_date'>
                        <input type='text' class="form-control" id="datevalue" readonly="" />
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </div>

                <div class="panel-body">
                    <table class="table table-striped table-bordered table-hover" id="tbl_blog">
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script type="text/javascript">

function tableData(val = ''){
    console.log(val);
    oTable = $('#tbl_blog').DataTable({
        "processing": true,
        "serverSide": true,
        "language": {
            "aria": {
                "sortAscending": ": click to sort column ascending",
                "sortDescending": ": click to sort column descending"
            },
            "emptyTable": "No data available in table",
            "info": "Showing _START_ to _END_ of _TOTAL_ entries",
            "infoEmpty": "No entries found",
            "infoFiltered": "(filtered1 from _MAX_ total entries)",
            "lengthMenu": "_MENU_ entries",
            "search": "Search:",
            "zeroRecords": "No matching records found"
        },
        "columns": [
            { "title": "Blog Name" ,"data": "blog_name"},
            { "title": "Blog Description" ,"data": "blog_description"},
            { "title": "Blog Date" ,"data": "blog_date"},
            // { "title": "Action" ,"data": "action", searchble: false, sortable:false }
        ],
        "order": [
            [0, 'asc']
        ],
        "lengthMenu": [
            [10, 20, 50,100],
            [10, 20, 50,100]
        ],
        "ajax": {
            "url": "{{ route('blog.listdata') }}",
            "data": {status:val},
        },
    });
};

$(function(){
    tableData();

    $('#filter_date').datepicker({
        format: "yyyy-mm-dd",
        autoclose: true,
    });

    $('#filter_date').change(function() {
        var status = $("#datevalue").val();
        $('#tbl_blog').dataTable().fnDestroy();
        tableData(status);
    });
});

</script>
@endpush

resources/views/pages/blog/view.blade.php
@extends('layouts.app')
@section('title') {{ $headTitle }} @endsection

@section('breadcrumb')
{!! Breadcrumbs::render('view_store', $store) !!}
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title" id="basic-layout-form">{{ $headTitle }}</h4>
                <a class="heading-elements-toggle">
                    <i class="la la-ellipsis-v font-medium-3"></i>
                </a>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card-content collapse show">
                        <div class="card-body">
                            <dl class="row">
                                <dt class="col-md-3 font-small-4">Store Name:</dt>
                                <dd class="col-md-4 font-small-4">{{ $store->store_name }}</dd>
                            </dl>

                            <dl class="row">
                            	<dt class="col-md-3 font-small-4">Store Description:</dt>
                                <dd class="col-md-4 font-small-4">{{ $store->store_description }}</dd>
                            </dl>

                            <dl class="row">
                                <dt class="col-md-3 font-small-4">Store Location:</dt>
                                <dd class="col-md-4 font-small-4">{{ $store->store_location }}</dd>
                            </dl>

                            <dl class="row">
                                <dt class="col-md-3 font-small-4">Store URL:</dt>
                                <dd class="col-md-4 font-small-4">{{ $store->url }}</dd>
                            </dl>

                            <dl class="row">
	                        	<dt class="col-md-3 font-small-4">Store Logo:</dt>
                                <dd class="col-md-4">
	                               <img width="200px" height="150px" src="{{ checkImage(7,$store->store_logo) }}" alt="" class="img-responsive" id="store_logo" name="store_logo">
                                </dd>
		                    </dl>

                            <dl class="row">
                                <dt class="col-md-3 font-small-4">Store Banner:</dt>
                                <dd class="col-md-4">
                                   <img width="200px" height="150px" src="{{ checkImage(7,$store->store_banner) }}" alt="" class="img-responsive" id="store_banner" name="store_banner">
                                </dd>
                            </dl>
                            
                            <div class="margiv-top-10">
                                <a href="{{ route('store.index') }}"><button type="button" class="btn btn-danger mr-1"><i class="fa fa-arrow-left"></i> Back</button></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection